//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfLeagueApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int CourseID { get; set; }
        public int MatchID { get; set; }
        public string CourseName { get; set; }
        public int Hole1Par { get; set; }
        public int Hole1Handicap { get; set; }
        public int Hole2Par { get; set; }
        public int Hole2Handicap { get; set; }
        public int Hole3Par { get; set; }
        public int Hole3Handicap { get; set; }
        public int Hole4par { get; set; }
        public int Hole4Handicap { get; set; }
        public int Hole5Par { get; set; }
        public int Hole5Handicap { get; set; }
        public int Hole6Par { get; set; }
        public int Hole6Handicap { get; set; }
        public int Hole7Par { get; set; }
        public int Hole7Handicap { get; set; }
        public int Hole8Par { get; set; }
        public int Hole8Handicap { get; set; }
        public int Hole9Par { get; set; }
        public int Hole9Handicap { get; set; }
    }
}
