//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfLeagueApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolfLeagueDBEntities : DbContext
    {
        public GolfLeagueDBEntities()
            : base("name=GolfLeagueDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<HandicapMethod> HandicapMethods { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<LeagueYear> LeagueYears { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<MaxScore> MaxScores { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PointSytem> PointSytems { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeamMember> TeamMembers { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
