//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfLeagueApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public int RoundID { get; set; }
        public System.DateTime RoundDate { get; set; }
        public int Hole1Strokes { get; set; }
        public int Hole2Stokes { get; set; }
        public int Hole3Strokes { get; set; }
        public int Hole4Strokes { get; set; }
        public int Hole5Strokes { get; set; }
        public int Hole6Strokes { get; set; }
        public int Hole7Strokes { get; set; }
        public int Hole8Strokes { get; set; }
        public int Hole9Strokes { get; set; }
        public int TotalStrokes { get; set; }
        public int TotalPutts { get; set; }
        public int PlayerID { get; set; }
        public int CourseID { get; set; }
        public int MatchID { get; set; }
    }
}
